// Code generated by modgen. DO NOT EDIT.
package home

import "encoding/json"

// 确保 json 包被使用
var _ = json.Marshal

// ==================== ProfileSection 生成代码 ====================

// 位掩码常量
const (
	_ProfileSection_Name_Bit       uint64 = 1 << 0
	_ProfileSection_Gold_Bit       uint64 = 1 << 1
	_ProfileSection_Power_Bit      uint64 = 1 << 2
	_ProfileSection_BuildLevel_Bit uint64 = 1 << 3
)

func (m *ProfileSection) Key() string   { return "profile" }
func (m *ProfileSection) IsDirty() bool { return m.dirty != 0 }
func (m *ProfileSection) ClearDirty()   { m.dirty = 0 }

func (m *ProfileSection) Marshal() ([]byte, error) {
	return json.Marshal(m)
}

func (m *ProfileSection) Unmarshal(data []byte) error {
	return json.Unmarshal(data, m)
}

// DirtyFields 返回脏字段的 JSON key 和当前值（用于字段级 $set）
func (m *ProfileSection) DirtyFields() map[string]interface{} {
	fields := make(map[string]interface{})
	if m.dirty&_ProfileSection_Name_Bit != 0 {
		fields["name"] = m.Name
	}
	if m.dirty&_ProfileSection_Gold_Bit != 0 {
		fields["gold"] = m.Gold
	}
	if m.dirty&_ProfileSection_Power_Bit != 0 {
		fields["power"] = m.Power
	}
	if m.dirty&_ProfileSection_BuildLevel_Bit != 0 {
		fields["build_level"] = m.BuildLevel
	}
	return fields
}

func (m *ProfileSection) GetName() string { return m.Name }
func (m *ProfileSection) SetName(v string) {
	m.Name = v
	m.dirty |= _ProfileSection_Name_Bit
}

func (m *ProfileSection) GetGold() int32 { return m.Gold }
func (m *ProfileSection) SetGold(v int32) {
	m.Gold = v
	m.dirty |= _ProfileSection_Gold_Bit
}
func (m *ProfileSection) AddGold(delta int32) {
	m.Gold += delta
	m.dirty |= _ProfileSection_Gold_Bit
}

func (m *ProfileSection) GetPower() int32 { return m.Power }
func (m *ProfileSection) SetPower(v int32) {
	m.Power = v
	m.dirty |= _ProfileSection_Power_Bit
}
func (m *ProfileSection) AddPower(delta int32) {
	m.Power += delta
	m.dirty |= _ProfileSection_Power_Bit
}

func (m *ProfileSection) GetBuildLevel() int32 { return m.BuildLevel }
func (m *ProfileSection) SetBuildLevel(v int32) {
	m.BuildLevel = v
	m.dirty |= _ProfileSection_BuildLevel_Bit
}

// ==================== BagSection 生成代码 ====================

// 位掩码常量
const (
	_BagSection_Items_Bit uint64 = 1 << 0
)

func (m *BagSection) Key() string   { return "bag" }
func (m *BagSection) IsDirty() bool { return m.dirty != 0 }
func (m *BagSection) ClearDirty()   { m.dirty = 0 }

func (m *BagSection) Marshal() ([]byte, error) {
	return json.Marshal(m)
}

func (m *BagSection) Unmarshal(data []byte) error {
	return json.Unmarshal(data, m)
}

// DirtyFields 返回脏字段的 JSON key 和当前值（用于字段级 $set）
func (m *BagSection) DirtyFields() map[string]interface{} {
	fields := make(map[string]interface{})
	if m.dirty&_BagSection_Items_Bit != 0 {
		fields["items"] = m.Items
	}
	return fields
}

func (m *BagSection) GetItems() map[int32]int32 { return m.Items }
func (m *BagSection) SetItems(v map[int32]int32) {
	m.Items = v
	m.dirty |= _BagSection_Items_Bit
}
func (m *BagSection) GetItemsKey(key int32) int32 {
	if m.Items == nil {
		return int32(0)
	}
	return m.Items[key]
}
func (m *BagSection) SetItemsKey(key int32, val int32) {
	if m.Items == nil {
		m.Items = make(map[int32]int32)
	}
	m.Items[key] = val
	m.dirty |= _BagSection_Items_Bit
}
func (m *BagSection) DelItemsKey(key int32) {
	if m.Items != nil {
		delete(m.Items, key)
		m.dirty |= _BagSection_Items_Bit
	}
}

// ==================== BuildsSection 生成代码 ====================

// 位掩码常量
const (
	_BuildsSection_Builds_Bit uint64 = 1 << 0
)

func (m *BuildsSection) Key() string   { return "builds" }
func (m *BuildsSection) IsDirty() bool { return m.dirty != 0 }
func (m *BuildsSection) ClearDirty()   { m.dirty = 0 }

func (m *BuildsSection) Marshal() ([]byte, error) {
	return json.Marshal(m)
}

func (m *BuildsSection) Unmarshal(data []byte) error {
	return json.Unmarshal(data, m)
}

// DirtyFields 返回脏字段的 JSON key 和当前值（用于字段级 $set）
func (m *BuildsSection) DirtyFields() map[string]interface{} {
	fields := make(map[string]interface{})
	if m.dirty&_BuildsSection_Builds_Bit != 0 {
		fields["builds"] = m.Builds
	}
	return fields
}

func (m *BuildsSection) GetBuilds() map[string]int32 { return m.Builds }
func (m *BuildsSection) SetBuilds(v map[string]int32) {
	m.Builds = v
	m.dirty |= _BuildsSection_Builds_Bit
}
func (m *BuildsSection) GetBuildsKey(key string) int32 {
	if m.Builds == nil {
		return int32(0)
	}
	return m.Builds[key]
}
func (m *BuildsSection) SetBuildsKey(key string, val int32) {
	if m.Builds == nil {
		m.Builds = make(map[string]int32)
	}
	m.Builds[key] = val
	m.dirty |= _BuildsSection_Builds_Bit
}
func (m *BuildsSection) DelBuildsKey(key string) {
	if m.Builds != nil {
		delete(m.Builds, key)
		m.dirty |= _BuildsSection_Builds_Bit
	}
}
