// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: api/proto/kit/envelope.proto

package kit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope 是所有 Actor 间通信的顶层容器。
// 它提供了分布式追踪和元数据上下文。
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TraceId   string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 分布式追踪 ID
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // Unix 时间戳 (纳秒)
	// 负载可以是 EdgeLetter (来自/发往客户端) 或 MeshLetter (内部)。
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Edge
	//	*Envelope_Mesh
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_proto_kit_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetEdge() *EdgeLetter {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Edge); ok {
			return x.Edge
		}
	}
	return nil
}

func (x *Envelope) GetMesh() *MeshLetter {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Mesh); ok {
			return x.Mesh
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Edge struct {
	Edge *EdgeLetter `protobuf:"bytes,3,opt,name=edge,proto3,oneof"`
}

type Envelope_Mesh struct {
	Mesh *MeshLetter `protobuf:"bytes,4,opt,name=mesh,proto3,oneof"`
}

func (*Envelope_Edge) isEnvelope_Payload() {}

func (*Envelope_Mesh) isEnvelope_Payload() {}

// EdgeLetter 封装了源自或发往外部客户端 (Edge) 的消息。
// 对应设计中的 "ClientLetter" 概念。
type EdgeLetter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       int32                  `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`       // 协议 ID (例如 1001 代表登录)
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`                             // 具体消息的序列化 Protobuf体
	SessionId     int64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 网关 Channel/Session ID (用于路由响应)
	PlayerId      string                 `protobuf:"bytes,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`     // 关联的玩家 ID (认证后填充)
	MsgNo         int32                  `protobuf:"varint,5,opt,name=msg_no,json=msgNo,proto3" json:"msg_no,omitempty"`             // 客户端序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeLetter) Reset() {
	*x = EdgeLetter{}
	mi := &file_api_proto_kit_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeLetter) ProtoMessage() {}

func (x *EdgeLetter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeLetter.ProtoReflect.Descriptor instead.
func (*EdgeLetter) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeLetter) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EdgeLetter) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EdgeLetter) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *EdgeLetter) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EdgeLetter) GetMsgNo() int32 {
	if x != nil {
		return x.MsgNo
	}
	return 0
}

// MeshLetter 封装了内部控制命令或系统消息。
// 对应设计中的 "SystemLetter" 概念。
type MeshLetter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`                                          // 命令动词: KICK, STOP, RELOAD 等
	Params        []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`                                    // 序列化参数 (可选)
	SenderService string                 `protobuf:"bytes,3,opt,name=sender_service,json=senderService,proto3" json:"sender_service,omitempty"` // 发送方服务名称
	TargetService string                 `protobuf:"bytes,4,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // 目标服务名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshLetter) Reset() {
	*x = MeshLetter{}
	mi := &file_api_proto_kit_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshLetter) ProtoMessage() {}

func (x *MeshLetter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshLetter.ProtoReflect.Descriptor instead.
func (*MeshLetter) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *MeshLetter) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *MeshLetter) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MeshLetter) GetSenderService() string {
	if x != nil {
		return x.SenderService
	}
	return ""
}

func (x *MeshLetter) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

var File_api_proto_kit_envelope_proto protoreflect.FileDescriptor

const file_api_proto_kit_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/kit/envelope.proto\x12\x03kit\"\x9c\x01\n" +
	"\bEnvelope\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x04edge\x18\x03 \x01(\v2\x0f.kit.EdgeLetterH\x00R\x04edge\x12%\n" +
	"\x04mesh\x18\x04 \x01(\v2\x0f.kit.MeshLetterH\x00R\x04meshB\t\n" +
	"\apayload\"\x8e\x01\n" +
	"\n" +
	"EdgeLetter\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\x05R\amsgType\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\tR\bplayerId\x12\x15\n" +
	"\x06msg_no\x18\x05 \x01(\x05R\x05msgNo\"\x84\x01\n" +
	"\n" +
	"MeshLetter\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\x12%\n" +
	"\x0esender_service\x18\x03 \x01(\tR\rsenderService\x12%\n" +
	"\x0etarget_service\x18\x04 \x01(\tR\rtargetServiceB\x15Z\x13overmind/pkg/pb/kitb\x06proto3"

var (
	file_api_proto_kit_envelope_proto_rawDescOnce sync.Once
	file_api_proto_kit_envelope_proto_rawDescData []byte
)

func file_api_proto_kit_envelope_proto_rawDescGZIP() []byte {
	file_api_proto_kit_envelope_proto_rawDescOnce.Do(func() {
		file_api_proto_kit_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kit_envelope_proto_rawDesc), len(file_api_proto_kit_envelope_proto_rawDesc)))
	})
	return file_api_proto_kit_envelope_proto_rawDescData
}

var file_api_proto_kit_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_kit_envelope_proto_goTypes = []any{
	(*Envelope)(nil),   // 0: kit.Envelope
	(*EdgeLetter)(nil), // 1: kit.EdgeLetter
	(*MeshLetter)(nil), // 2: kit.MeshLetter
}
var file_api_proto_kit_envelope_proto_depIdxs = []int32{
	1, // 0: kit.Envelope.edge:type_name -> kit.EdgeLetter
	2, // 1: kit.Envelope.mesh:type_name -> kit.MeshLetter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_kit_envelope_proto_init() }
func file_api_proto_kit_envelope_proto_init() {
	if File_api_proto_kit_envelope_proto != nil {
		return
	}
	file_api_proto_kit_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Edge)(nil),
		(*Envelope_Mesh)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kit_envelope_proto_rawDesc), len(file_api_proto_kit_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_kit_envelope_proto_goTypes,
		DependencyIndexes: file_api_proto_kit_envelope_proto_depIdxs,
		MessageInfos:      file_api_proto_kit_envelope_proto_msgTypes,
	}.Build()
	File_api_proto_kit_envelope_proto = out.File
	file_api_proto_kit_envelope_proto_goTypes = nil
	file_api_proto_kit_envelope_proto_depIdxs = nil
}
