// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: api/proto/kit/internal.proto

package kit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorldRouteRequest 是发给 world 实体的统一路由请求。
// msg_type 继续沿用客户端协议号，payload 承载真正的 protobuf 消息体。
type WorldRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldRouteRequest) Reset() {
	*x = WorldRouteRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldRouteRequest) ProtoMessage() {}

func (x *WorldRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldRouteRequest.ProtoReflect.Descriptor instead.
func (*WorldRouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{0}
}

func (x *WorldRouteRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *WorldRouteRequest) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *WorldRouteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// WorldEnterSceneRequest 对应“进入场景”这类需要 gateway 注入会话上下文的请求。
type WorldEnterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	SceneId       int64                  `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldEnterSceneRequest) Reset() {
	*x = WorldEnterSceneRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldEnterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldEnterSceneRequest) ProtoMessage() {}

func (x *WorldEnterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldEnterSceneRequest.ProtoReflect.Descriptor instead.
func (*WorldEnterSceneRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{1}
}

func (x *WorldEnterSceneRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *WorldEnterSceneRequest) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *WorldEnterSceneRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldEnterSceneRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// WorldDispatchBatch 是 world 回给调用方的统一批量投递结果。
type WorldDispatchBatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Messages      []*WorldDispatchMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldDispatchBatch) Reset() {
	*x = WorldDispatchBatch{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldDispatchBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldDispatchBatch) ProtoMessage() {}

func (x *WorldDispatchBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldDispatchBatch.ProtoReflect.Descriptor instead.
func (*WorldDispatchBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{2}
}

func (x *WorldDispatchBatch) GetMessages() []*WorldDispatchMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type WorldDispatchMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []int64                `protobuf:"varint,1,rep,packed,name=recipients,proto3" json:"recipients,omitempty"`
	MsgType       int32                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldDispatchMessage) Reset() {
	*x = WorldDispatchMessage{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldDispatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldDispatchMessage) ProtoMessage() {}

func (x *WorldDispatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldDispatchMessage.ProtoReflect.Descriptor instead.
func (*WorldDispatchMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{3}
}

func (x *WorldDispatchMessage) GetRecipients() []int64 {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *WorldDispatchMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *WorldDispatchMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// WorldLoginRequest 对应 channel/gateway 发给 world 的登录第一跳。
type WorldLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       int64                  `protobuf:"varint,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	ConnId        string                 `protobuf:"bytes,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldLoginRequest) Reset() {
	*x = WorldLoginRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldLoginRequest) ProtoMessage() {}

func (x *WorldLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldLoginRequest.ProtoReflect.Descriptor instead.
func (*WorldLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{4}
}

func (x *WorldLoginRequest) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WorldLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *WorldLoginRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type WorldLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WorldId       int64                  `protobuf:"varint,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldLoginResponse) Reset() {
	*x = WorldLoginResponse{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldLoginResponse) ProtoMessage() {}

func (x *WorldLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldLoginResponse.ProtoReflect.Descriptor instead.
func (*WorldLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{5}
}

func (x *WorldLoginResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *WorldLoginResponse) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *WorldLoginResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type WorldError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldError) Reset() {
	*x = WorldError{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldError) ProtoMessage() {}

func (x *WorldError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldError.ProtoReflect.Descriptor instead.
func (*WorldError) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{6}
}

func (x *WorldError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PlayerBindRequest 由 gateway 在登录成功后发给 player，用于建立在线会话绑定。
type PlayerBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WorldId       int64                  `protobuf:"varint,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	ConnId        string                 `protobuf:"bytes,4,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindRequest) Reset() {
	*x = PlayerBindRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindRequest) ProtoMessage() {}

func (x *PlayerBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindRequest.ProtoReflect.Descriptor instead.
func (*PlayerBindRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerBindRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBindRequest) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerBindRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlayerBindRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type PlayerBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WorldId       int64                  `protobuf:"varint,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	ExpiredConnId string                 `protobuf:"bytes,4,opt,name=expired_conn_id,json=expiredConnId,proto3" json:"expired_conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBindResponse) Reset() {
	*x = PlayerBindResponse{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBindResponse) ProtoMessage() {}

func (x *PlayerBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBindResponse.ProtoReflect.Descriptor instead.
func (*PlayerBindResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerBindResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBindResponse) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerBindResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *PlayerBindResponse) GetExpiredConnId() string {
	if x != nil {
		return x.ExpiredConnId
	}
	return ""
}

// PlayerUnbindRequest 由 gateway 在连接断开时发给 player，用于清理在线绑定。
type PlayerUnbindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUnbindRequest) Reset() {
	*x = PlayerUnbindRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnbindRequest) ProtoMessage() {}

func (x *PlayerUnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnbindRequest.ProtoReflect.Descriptor instead.
func (*PlayerUnbindRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerUnbindRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerUnbindRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type PlayerUnbindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUnbindResponse) Reset() {
	*x = PlayerUnbindResponse{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUnbindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUnbindResponse) ProtoMessage() {}

func (x *PlayerUnbindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUnbindResponse.ProtoReflect.Descriptor instead.
func (*PlayerUnbindResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerUnbindResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerUnbindResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

// PlayerLoginRequest 对应 world 发给 player 的登录第二跳。
type PlayerLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WorldId       int64                  `protobuf:"varint,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	ConnId        string                 `protobuf:"bytes,4,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginRequest) Reset() {
	*x = PlayerLoginRequest{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginRequest) ProtoMessage() {}

func (x *PlayerLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginRequest.ProtoReflect.Descriptor instead.
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerLoginRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerLoginRequest) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlayerLoginRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type PlayerLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	WorldId       int64                  `protobuf:"varint,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	ConnId        string                 `protobuf:"bytes,3,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	ExpiredConnId string                 `protobuf:"bytes,4,opt,name=expired_conn_id,json=expiredConnId,proto3" json:"expired_conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLoginResponse) Reset() {
	*x = PlayerLoginResponse{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLoginResponse) ProtoMessage() {}

func (x *PlayerLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLoginResponse.ProtoReflect.Descriptor instead.
func (*PlayerLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerLoginResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerLoginResponse) GetWorldId() int64 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *PlayerLoginResponse) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *PlayerLoginResponse) GetExpiredConnId() string {
	if x != nil {
		return x.ExpiredConnId
	}
	return ""
}

type PlayerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerError) Reset() {
	*x = PlayerError{}
	mi := &file_api_proto_kit_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerError) ProtoMessage() {}

func (x *PlayerError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_kit_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerError.ProtoReflect.Descriptor instead.
func (*PlayerError) Descriptor() ([]byte, []int) {
	return file_api_proto_kit_internal_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_proto_kit_internal_proto protoreflect.FileDescriptor

const file_api_proto_kit_internal_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/kit/internal.proto\x12\x03kit\"e\n" +
	"\x11WorldRouteRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"p\n" +
	"\x16WorldEnterSceneRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x03R\asceneId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\"K\n" +
	"\x12WorldDispatchBatch\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.kit.WorldDispatchMessageR\bmessages\"k\n" +
	"\x14WorldDispatchMessage\x12\x1e\n" +
	"\n" +
	"recipients\x18\x01 \x03(\x03R\n" +
	"recipients\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x05R\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"a\n" +
	"\x11WorldLoginRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\x03R\aworldId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x17\n" +
	"\aconn_id\x18\x03 \x01(\tR\x06connId\"e\n" +
	"\x12WorldLoginResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\x03R\aworldId\x12\x17\n" +
	"\aconn_id\x18\x03 \x01(\tR\x06connId\"$\n" +
	"\n" +
	"WorldError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"~\n" +
	"\x11PlayerBindRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\x03R\aworldId\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x17\n" +
	"\aconn_id\x18\x04 \x01(\tR\x06connId\"\x8d\x01\n" +
	"\x12PlayerBindResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\x03R\aworldId\x12\x17\n" +
	"\aconn_id\x18\x03 \x01(\tR\x06connId\x12&\n" +
	"\x0fexpired_conn_id\x18\x04 \x01(\tR\rexpiredConnId\"K\n" +
	"\x13PlayerUnbindRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\"L\n" +
	"\x14PlayerUnbindResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\tR\x06connId\"\x7f\n" +
	"\x12PlayerLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\x03R\aworldId\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x17\n" +
	"\aconn_id\x18\x04 \x01(\tR\x06connId\"\x8e\x01\n" +
	"\x13PlayerLoginResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\x03R\aworldId\x12\x17\n" +
	"\aconn_id\x18\x03 \x01(\tR\x06connId\x12&\n" +
	"\x0fexpired_conn_id\x18\x04 \x01(\tR\rexpiredConnId\"%\n" +
	"\vPlayerError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB\x15Z\x13overmind/pkg/pb/kitb\x06proto3"

var (
	file_api_proto_kit_internal_proto_rawDescOnce sync.Once
	file_api_proto_kit_internal_proto_rawDescData []byte
)

func file_api_proto_kit_internal_proto_rawDescGZIP() []byte {
	file_api_proto_kit_internal_proto_rawDescOnce.Do(func() {
		file_api_proto_kit_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_kit_internal_proto_rawDesc), len(file_api_proto_kit_internal_proto_rawDesc)))
	})
	return file_api_proto_kit_internal_proto_rawDescData
}

var file_api_proto_kit_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_kit_internal_proto_goTypes = []any{
	(*WorldRouteRequest)(nil),      // 0: kit.WorldRouteRequest
	(*WorldEnterSceneRequest)(nil), // 1: kit.WorldEnterSceneRequest
	(*WorldDispatchBatch)(nil),     // 2: kit.WorldDispatchBatch
	(*WorldDispatchMessage)(nil),   // 3: kit.WorldDispatchMessage
	(*WorldLoginRequest)(nil),      // 4: kit.WorldLoginRequest
	(*WorldLoginResponse)(nil),     // 5: kit.WorldLoginResponse
	(*WorldError)(nil),             // 6: kit.WorldError
	(*PlayerBindRequest)(nil),      // 7: kit.PlayerBindRequest
	(*PlayerBindResponse)(nil),     // 8: kit.PlayerBindResponse
	(*PlayerUnbindRequest)(nil),    // 9: kit.PlayerUnbindRequest
	(*PlayerUnbindResponse)(nil),   // 10: kit.PlayerUnbindResponse
	(*PlayerLoginRequest)(nil),     // 11: kit.PlayerLoginRequest
	(*PlayerLoginResponse)(nil),    // 12: kit.PlayerLoginResponse
	(*PlayerError)(nil),            // 13: kit.PlayerError
}
var file_api_proto_kit_internal_proto_depIdxs = []int32{
	3, // 0: kit.WorldDispatchBatch.messages:type_name -> kit.WorldDispatchMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_kit_internal_proto_init() }
func file_api_proto_kit_internal_proto_init() {
	if File_api_proto_kit_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_kit_internal_proto_rawDesc), len(file_api_proto_kit_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_kit_internal_proto_goTypes,
		DependencyIndexes: file_api_proto_kit_internal_proto_depIdxs,
		MessageInfos:      file_api_proto_kit_internal_proto_msgTypes,
	}.Build()
	File_api_proto_kit_internal_proto = out.File
	file_api_proto_kit_internal_proto_goTypes = nil
	file_api_proto_kit_internal_proto_depIdxs = nil
}
