// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: api/proto/game/game.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SceneId       int64                  `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_api_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *Player) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Monster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SceneId       int64                  `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	X             int32                  `protobuf:"varint,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,7,opt,name=y,proto3" json:"y,omitempty"`
	Dead          bool                   `protobuf:"varint,8,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monster) Reset() {
	*x = Monster{}
	mi := &file_api_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monster) ProtoMessage() {}

func (x *Monster) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monster.ProtoReflect.Descriptor instead.
func (*Monster) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *Monster) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Monster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Monster) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *Monster) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Monster) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Monster) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Monster) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Monster) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

type EnterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneRequest) Reset() {
	*x = EnterSceneRequest{}
	mi := &file_api_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneRequest) ProtoMessage() {}

func (x *EnterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneRequest.ProtoReflect.Descriptor instead.
func (*EnterSceneRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{2}
}

type SceneSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       int64                  `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	Self          *Player                `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Monsters      []*Monster             `protobuf:"bytes,4,rep,name=monsters,proto3" json:"monsters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneSnapshot) Reset() {
	*x = SceneSnapshot{}
	mi := &file_api_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneSnapshot) ProtoMessage() {}

func (x *SceneSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneSnapshot.ProtoReflect.Descriptor instead.
func (*SceneSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *SceneSnapshot) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneSnapshot) GetSelf() *Player {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *SceneSnapshot) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *SceneSnapshot) GetMonsters() []*Monster {
	if x != nil {
		return x.Monsters
	}
	return nil
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_api_proto_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *MoveRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MoveBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SceneId       int64                  `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveBroadcast) Reset() {
	*x = MoveBroadcast{}
	mi := &file_api_proto_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveBroadcast) ProtoMessage() {}

func (x *MoveBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveBroadcast.ProtoReflect.Descriptor instead.
func (*MoveBroadcast) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *MoveBroadcast) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MoveBroadcast) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *MoveBroadcast) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveBroadcast) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AttackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackRequest) Reset() {
	*x = AttackRequest{}
	mi := &file_api_proto_game_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackRequest) ProtoMessage() {}

func (x *AttackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackRequest.ProtoReflect.Descriptor instead.
func (*AttackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *AttackRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type CombatBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    int64                  `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SceneId       int64                  `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	TargetHp      int32                  `protobuf:"varint,5,opt,name=target_hp,json=targetHp,proto3" json:"target_hp,omitempty"`
	Dead          bool                   `protobuf:"varint,6,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatBroadcast) Reset() {
	*x = CombatBroadcast{}
	mi := &file_api_proto_game_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatBroadcast) ProtoMessage() {}

func (x *CombatBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatBroadcast.ProtoReflect.Descriptor instead.
func (*CombatBroadcast) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *CombatBroadcast) GetAttackerId() int64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *CombatBroadcast) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CombatBroadcast) GetSceneId() int64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CombatBroadcast) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *CombatBroadcast) GetTargetHp() int32 {
	if x != nil {
		return x.TargetHp
	}
	return 0
}

func (x *CombatBroadcast) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_proto_game_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_game_game_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_game_game_proto protoreflect.FileDescriptor

const file_api_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/game/game.proto\x12\x04game\"c\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bscene_id\x18\x03 \x01(\x03R\asceneId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\"\x9f\x01\n" +
	"\aMonster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bscene_id\x18\x03 \x01(\x03R\asceneId\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\f\n" +
	"\x01x\x18\x06 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x05R\x01y\x12\x12\n" +
	"\x04dead\x18\b \x01(\bR\x04dead\"\x13\n" +
	"\x11EnterSceneRequest\"\x9f\x01\n" +
	"\rSceneSnapshot\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x03R\asceneId\x12 \n" +
	"\x04self\x18\x02 \x01(\v2\f.game.PlayerR\x04self\x12&\n" +
	"\aplayers\x18\x03 \x03(\v2\f.game.PlayerR\aplayers\x12)\n" +
	"\bmonsters\x18\x04 \x03(\v2\r.game.MonsterR\bmonsters\")\n" +
	"\vMoveRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"c\n" +
	"\rMoveBroadcast\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x03R\asceneId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\",\n" +
	"\rAttackRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\"\xb3\x01\n" +
	"\x0fCombatBroadcast\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x03R\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x19\n" +
	"\bscene_id\x18\x03 \x01(\x03R\asceneId\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x1b\n" +
	"\ttarget_hp\x18\x05 \x01(\x05R\btargetHp\x12\x12\n" +
	"\x04dead\x18\x06 \x01(\bR\x04dead\"S\n" +
	"\rErrorResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessageB\x1dZ\x1bovermind/pkg/pb/game;gamepbb\x06proto3"

var (
	file_api_proto_game_game_proto_rawDescOnce sync.Once
	file_api_proto_game_game_proto_rawDescData []byte
)

func file_api_proto_game_game_proto_rawDescGZIP() []byte {
	file_api_proto_game_game_proto_rawDescOnce.Do(func() {
		file_api_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_game_game_proto_rawDesc), len(file_api_proto_game_game_proto_rawDesc)))
	})
	return file_api_proto_game_game_proto_rawDescData
}

var file_api_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_game_game_proto_goTypes = []any{
	(*Player)(nil),            // 0: game.Player
	(*Monster)(nil),           // 1: game.Monster
	(*EnterSceneRequest)(nil), // 2: game.EnterSceneRequest
	(*SceneSnapshot)(nil),     // 3: game.SceneSnapshot
	(*MoveRequest)(nil),       // 4: game.MoveRequest
	(*MoveBroadcast)(nil),     // 5: game.MoveBroadcast
	(*AttackRequest)(nil),     // 6: game.AttackRequest
	(*CombatBroadcast)(nil),   // 7: game.CombatBroadcast
	(*ErrorResponse)(nil),     // 8: game.ErrorResponse
}
var file_api_proto_game_game_proto_depIdxs = []int32{
	0, // 0: game.SceneSnapshot.self:type_name -> game.Player
	0, // 1: game.SceneSnapshot.players:type_name -> game.Player
	1, // 2: game.SceneSnapshot.monsters:type_name -> game.Monster
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_game_game_proto_init() }
func file_api_proto_game_game_proto_init() {
	if File_api_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_game_game_proto_rawDesc), len(file_api_proto_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_game_game_proto_goTypes,
		DependencyIndexes: file_api_proto_game_game_proto_depIdxs,
		MessageInfos:      file_api_proto_game_game_proto_msgTypes,
	}.Build()
	File_api_proto_game_game_proto = out.File
	file_api_proto_game_game_proto_goTypes = nil
	file_api_proto_game_game_proto_depIdxs = nil
}
