// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgID 定义客户端与服务端之间的协议号绑定枚举
type MsgID int32

const (
	MsgID_MSG_NONE MsgID = 0
	// 基础系统 / 网关本地协议 (1000 - 9999)
	MsgID_MSG_C2S_LOGIN         MsgID = 1001
	MsgID_MSG_S2C_LOGIN_RES     MsgID = 1002
	MsgID_MSG_C2S_HEARTBEAT     MsgID = 1003
	MsgID_MSG_S2C_HEARTBEAT_RES MsgID = 1004
	// 逻辑系统 / 玩家业务协议 (10000 - 19999)
	MsgID_MSG_S2C_SYNC_DATA         MsgID = 10001
	MsgID_MSG_C2S_BUILD_UPGRADE     MsgID = 10005
	MsgID_MSG_S2C_BUILD_UPGRADE_RES MsgID = 10006
	MsgID_MSG_C2S_SUBSCRIBE_MAP     MsgID = 10010
	MsgID_MSG_S2C_MAP_BROADCAST     MsgID = 10011
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:     "MSG_NONE",
		1001:  "MSG_C2S_LOGIN",
		1002:  "MSG_S2C_LOGIN_RES",
		1003:  "MSG_C2S_HEARTBEAT",
		1004:  "MSG_S2C_HEARTBEAT_RES",
		10001: "MSG_S2C_SYNC_DATA",
		10005: "MSG_C2S_BUILD_UPGRADE",
		10006: "MSG_S2C_BUILD_UPGRADE_RES",
		10010: "MSG_C2S_SUBSCRIBE_MAP",
		10011: "MSG_S2C_MAP_BROADCAST",
	}
	MsgID_value = map[string]int32{
		"MSG_NONE":                  0,
		"MSG_C2S_LOGIN":             1001,
		"MSG_S2C_LOGIN_RES":         1002,
		"MSG_C2S_HEARTBEAT":         1003,
		"MSG_S2C_HEARTBEAT_RES":     1004,
		"MSG_S2C_SYNC_DATA":         10001,
		"MSG_C2S_BUILD_UPGRADE":     10005,
		"MSG_S2C_BUILD_UPGRADE_RES": 10006,
		"MSG_C2S_SUBSCRIBE_MAP":     10010,
		"MSG_S2C_MAP_BROADCAST":     10011,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_game_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_api_game_game_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{0}
}

// C2S_Login 客户端请求登录 (ProtoID: 1001)
type C2S_Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Login) Reset() {
	*x = C2S_Login{}
	mi := &file_api_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login) ProtoMessage() {}

func (x *C2S_Login) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login.ProtoReflect.Descriptor instead.
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_Login) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *C2S_Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// S2C_LoginRes 服务端登录响应 (ProtoID: 1002)
type S2C_LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0 代表成功，非 0 代表失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_LoginRes) Reset() {
	*x = S2C_LoginRes{}
	mi := &file_api_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_LoginRes) ProtoMessage() {}

func (x *S2C_LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_LoginRes.ProtoReflect.Descriptor instead.
func (*S2C_LoginRes) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_LoginRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S2C_LoginRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// C2S_Heartbeat 客户端心跳请求 (ProtoID: 1003)
type C2S_Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Heartbeat) Reset() {
	*x = C2S_Heartbeat{}
	mi := &file_api_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Heartbeat) ProtoMessage() {}

func (x *C2S_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Heartbeat.ProtoReflect.Descriptor instead.
func (*C2S_Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Heartbeat) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

// S2C_HeartbeatRes 服务端心跳响应 (ProtoID: 1004)
type S2C_HeartbeatRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_HeartbeatRes) Reset() {
	*x = S2C_HeartbeatRes{}
	mi := &file_api_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_HeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_HeartbeatRes) ProtoMessage() {}

func (x *S2C_HeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_HeartbeatRes.ProtoReflect.Descriptor instead.
func (*S2C_HeartbeatRes) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_HeartbeatRes) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// S2C_SyncData 服务端个人数据增量同步 (ProtoID: 10001)
type S2C_SyncData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int32                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`                                    // 金币最新值
	Power         int32                  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`                                  // 战力最新值
	DirtyModules  []string               `protobuf:"bytes,3,rep,name=dirty_modules,json=dirtyModules,proto3" json:"dirty_modules,omitempty"` // 被污染的模块类型名称列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_SyncData) Reset() {
	*x = S2C_SyncData{}
	mi := &file_api_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SyncData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SyncData) ProtoMessage() {}

func (x *S2C_SyncData) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SyncData.ProtoReflect.Descriptor instead.
func (*S2C_SyncData) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_SyncData) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *S2C_SyncData) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *S2C_SyncData) GetDirtyModules() []string {
	if x != nil {
		return x.DirtyModules
	}
	return nil
}

// C2S_BuildUpgrade 客户端升级建筑请求 (ProtoID: 10005)
type C2S_BuildUpgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_BuildUpgrade) Reset() {
	*x = C2S_BuildUpgrade{}
	mi := &file_api_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_BuildUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BuildUpgrade) ProtoMessage() {}

func (x *C2S_BuildUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BuildUpgrade.ProtoReflect.Descriptor instead.
func (*C2S_BuildUpgrade) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_BuildUpgrade) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// S2C_BuildUpgradeRes 服务端升级建筑响应 (ProtoID: 10006)
type S2C_BuildUpgradeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_BuildUpgradeRes) Reset() {
	*x = S2C_BuildUpgradeRes{}
	mi := &file_api_game_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_BuildUpgradeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BuildUpgradeRes) ProtoMessage() {}

func (x *S2C_BuildUpgradeRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BuildUpgradeRes.ProtoReflect.Descriptor instead.
func (*S2C_BuildUpgradeRes) Descriptor() ([]byte, []int) {
	return file_api_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_BuildUpgradeRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *S2C_BuildUpgradeRes) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *S2C_BuildUpgradeRes) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_api_game_game_proto protoreflect.FileDescriptor

const file_api_game_game_proto_rawDesc = "" +
	"\n" +
	"\x13api/game/game.proto\x12\x03api\">\n" +
	"\tC2S_Login\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"4\n" +
	"\fS2C_LoginRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"0\n" +
	"\rC2S_Heartbeat\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"3\n" +
	"\x10S2C_HeartbeatRes\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"]\n" +
	"\fS2C_SyncData\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x05R\x04gold\x12\x14\n" +
	"\x05power\x18\x02 \x01(\x05R\x05power\x12#\n" +
	"\rdirty_modules\x18\x03 \x03(\tR\fdirtyModules\"-\n" +
	"\x10C2S_BuildUpgrade\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"Z\n" +
	"\x13S2C_BuildUpgradeRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level*\x81\x02\n" +
	"\x05MsgID\x12\f\n" +
	"\bMSG_NONE\x10\x00\x12\x12\n" +
	"\rMSG_C2S_LOGIN\x10\xe9\a\x12\x16\n" +
	"\x11MSG_S2C_LOGIN_RES\x10\xea\a\x12\x16\n" +
	"\x11MSG_C2S_HEARTBEAT\x10\xeb\a\x12\x1a\n" +
	"\x15MSG_S2C_HEARTBEAT_RES\x10\xec\a\x12\x16\n" +
	"\x11MSG_S2C_SYNC_DATA\x10\x91N\x12\x1a\n" +
	"\x15MSG_C2S_BUILD_UPGRADE\x10\x95N\x12\x1e\n" +
	"\x19MSG_S2C_BUILD_UPGRADE_RES\x10\x96N\x12\x1a\n" +
	"\x15MSG_C2S_SUBSCRIBE_MAP\x10\x9aN\x12\x1a\n" +
	"\x15MSG_S2C_MAP_BROADCAST\x10\x9bNB\x13Z\x11overmind/api/gameb\x06proto3"

var (
	file_api_game_game_proto_rawDescOnce sync.Once
	file_api_game_game_proto_rawDescData []byte
)

func file_api_game_game_proto_rawDescGZIP() []byte {
	file_api_game_game_proto_rawDescOnce.Do(func() {
		file_api_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_game_proto_rawDesc), len(file_api_game_game_proto_rawDesc)))
	})
	return file_api_game_game_proto_rawDescData
}

var file_api_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_game_game_proto_goTypes = []any{
	(MsgID)(0),                  // 0: api.MsgID
	(*C2S_Login)(nil),           // 1: api.C2S_Login
	(*S2C_LoginRes)(nil),        // 2: api.S2C_LoginRes
	(*C2S_Heartbeat)(nil),       // 3: api.C2S_Heartbeat
	(*S2C_HeartbeatRes)(nil),    // 4: api.S2C_HeartbeatRes
	(*S2C_SyncData)(nil),        // 5: api.S2C_SyncData
	(*C2S_BuildUpgrade)(nil),    // 6: api.C2S_BuildUpgrade
	(*S2C_BuildUpgradeRes)(nil), // 7: api.S2C_BuildUpgradeRes
}
var file_api_game_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_game_game_proto_init() }
func file_api_game_game_proto_init() {
	if File_api_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_game_proto_rawDesc), len(file_api_game_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_game_game_proto_goTypes,
		DependencyIndexes: file_api_game_game_proto_depIdxs,
		EnumInfos:         file_api_game_game_proto_enumTypes,
		MessageInfos:      file_api_game_game_proto_msgTypes,
	}.Build()
	File_api_game_game_proto = out.File
	file_api_game_game_proto_goTypes = nil
	file_api_game_game_proto_depIdxs = nil
}
