// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: api/proto/gateway/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgType 定义
// 范围: 1000 - 1999 用于网关/登录相关消息
type MsgType int32

const (
	MsgType_NONE            MsgType = 0
	MsgType_HEARTBEAT       MsgType = 1000
	MsgType_HANDSHAKE_REQ   MsgType = 1001
	MsgType_HANDSHAKE_RESP  MsgType = 1002
	MsgType_LOGIN_REQ       MsgType = 1003 // 转发给 Portal
	MsgType_LOGIN_RESP      MsgType = 1004 // 从 Portal 转发
	MsgType_ENTER_GAME_REQ  MsgType = 1005
	MsgType_ENTER_GAME_RESP MsgType = 1006
	MsgType_KICK_NOTIFY     MsgType = 1007
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:    "NONE",
		1000: "HEARTBEAT",
		1001: "HANDSHAKE_REQ",
		1002: "HANDSHAKE_RESP",
		1003: "LOGIN_REQ",
		1004: "LOGIN_RESP",
		1005: "ENTER_GAME_REQ",
		1006: "ENTER_GAME_RESP",
		1007: "KICK_NOTIFY",
	}
	MsgType_value = map[string]int32{
		"NONE":            0,
		"HEARTBEAT":       1000,
		"HANDSHAKE_REQ":   1001,
		"HANDSHAKE_RESP":  1002,
		"LOGIN_REQ":       1003,
		"LOGIN_RESP":      1004,
		"ENTER_GAME_REQ":  1005,
		"ENTER_GAME_RESP": 1006,
		"KICK_NOTIFY":     1007,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_gateway_gateway_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_api_proto_gateway_gateway_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

// Internal: Session 详情，从 Gateway 发送给 Portal/Game
type SessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ConnectTime   int64                  `protobuf:"varint,3,opt,name=connect_time,json=connectTime,proto3" json:"connect_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SessionState) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionState) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionState) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type HandshakeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeReq) Reset() {
	*x = HandshakeReq{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeReq) ProtoMessage() {}

func (x *HandshakeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeReq.ProtoReflect.Descriptor instead.
func (*HandshakeReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HandshakeReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type HandshakeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rt            int32                  `protobuf:"varint,1,opt,name=rt,proto3" json:"rt,omitempty"`
	ServerTime    string                 `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SessionKey    []byte                 `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"` // 初始 AES 密钥 / Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResp) Reset() {
	*x = HandshakeResp{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResp) ProtoMessage() {}

func (x *HandshakeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResp.ProtoReflect.Descriptor instead.
func (*HandshakeResp) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResp) GetRt() int32 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *HandshakeResp) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *HandshakeResp) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LoginReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rt            int32                  `protobuf:"varint,1,opt,name=rt,proto3" json:"rt,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResp) GetRt() int32 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EnterGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGameReq) Reset() {
	*x = EnterGameReq{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameReq) ProtoMessage() {}

func (x *EnterGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameReq.ProtoReflect.Descriptor instead.
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *EnterGameReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EnterGameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rt            int32                  `protobuf:"varint,1,opt,name=rt,proto3" json:"rt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterGameResp) Reset() {
	*x = EnterGameResp{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameResp) ProtoMessage() {}

func (x *EnterGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameResp.ProtoReflect.Descriptor instead.
func (*EnterGameResp) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *EnterGameResp) GetRt() int32 {
	if x != nil {
		return x.Rt
	}
	return 0
}

type KickNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        int32                  `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNotify) Reset() {
	*x = KickNotify{}
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNotify) ProtoMessage() {}

func (x *KickNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_gateway_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNotify.ProtoReflect.Descriptor instead.
func (*KickNotify) Descriptor() ([]byte, []int) {
	return file_api_proto_gateway_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *KickNotify) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_api_proto_gateway_gateway_proto protoreflect.FileDescriptor

const file_api_proto_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/gateway/gateway.proto\x12\agateway\"m\n" +
	"\fSessionState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12!\n" +
	"\fconnect_time\x18\x03 \x01(\x03R\vconnectTime\",\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"\\\n" +
	"\fHandshakeReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"a\n" +
	"\rHandshakeResp\x12\x0e\n" +
	"\x02rt\x18\x01 \x01(\x05R\x02rt\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime\x12\x1f\n" +
	"\vsession_key\x18\x03 \x01(\fR\n" +
	"sessionKey\"T\n" +
	"\bLoginReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"N\n" +
	"\tLoginResp\x12\x0e\n" +
	"\x02rt\x18\x01 \x01(\x05R\x02rt\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\"+\n" +
	"\fEnterGameReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x1f\n" +
	"\rEnterGameResp\x12\x0e\n" +
	"\x02rt\x18\x01 \x01(\x05R\x02rt\"$\n" +
	"\n" +
	"KickNotify\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\x05R\x06reason*\xaa\x01\n" +
	"\aMsgType\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\tHEARTBEAT\x10\xe8\a\x12\x12\n" +
	"\rHANDSHAKE_REQ\x10\xe9\a\x12\x13\n" +
	"\x0eHANDSHAKE_RESP\x10\xea\a\x12\x0e\n" +
	"\tLOGIN_REQ\x10\xeb\a\x12\x0f\n" +
	"\n" +
	"LOGIN_RESP\x10\xec\a\x12\x13\n" +
	"\x0eENTER_GAME_REQ\x10\xed\a\x12\x14\n" +
	"\x0fENTER_GAME_RESP\x10\xee\a\x12\x10\n" +
	"\vKICK_NOTIFY\x10\xef\aB\x19Z\x17overmind/pkg/pb/gatewayb\x06proto3"

var (
	file_api_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_api_proto_gateway_gateway_proto_rawDescData []byte
)

func file_api_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_api_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_api_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_gateway_gateway_proto_rawDesc), len(file_api_proto_gateway_gateway_proto_rawDesc)))
	})
	return file_api_proto_gateway_gateway_proto_rawDescData
}

var file_api_proto_gateway_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_gateway_gateway_proto_goTypes = []any{
	(MsgType)(0),          // 0: gateway.MsgType
	(*SessionState)(nil),  // 1: gateway.SessionState
	(*Heartbeat)(nil),     // 2: gateway.Heartbeat
	(*HandshakeReq)(nil),  // 3: gateway.HandshakeReq
	(*HandshakeResp)(nil), // 4: gateway.HandshakeResp
	(*LoginReq)(nil),      // 5: gateway.LoginReq
	(*LoginResp)(nil),     // 6: gateway.LoginResp
	(*EnterGameReq)(nil),  // 7: gateway.EnterGameReq
	(*EnterGameResp)(nil), // 8: gateway.EnterGameResp
	(*KickNotify)(nil),    // 9: gateway.KickNotify
}
var file_api_proto_gateway_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_gateway_gateway_proto_init() }
func file_api_proto_gateway_gateway_proto_init() {
	if File_api_proto_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_gateway_gateway_proto_rawDesc), len(file_api_proto_gateway_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_api_proto_gateway_gateway_proto_depIdxs,
		EnumInfos:         file_api_proto_gateway_gateway_proto_enumTypes,
		MessageInfos:      file_api_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_api_proto_gateway_gateway_proto = out.File
	file_api_proto_gateway_gateway_proto_goTypes = nil
	file_api_proto_gateway_gateway_proto_depIdxs = nil
}
