services:
  gateway:
    name: "gateway"
    host: "127.0.0.1"
    port: 8080
  portal:
    name: "portal"
    host: "127.0.0.1"
    port: 8081
  game:
    name: "game"
    host: "127.0.0.1"
    port: 8082

game:
  scene:
    width: 1000
    height: 1000
    cell_size: 100

log:
  level: "debug"
  encoding: "console"
