services:
  gateway:
    name: "gateway"
    host: "127.0.0.1"
    port: 8080
  portal:
    name: "portal"
    host: "127.0.0.1"
    port: 8081
  player:
    name: "player"
    host: "127.0.0.1"
    port: 8082
  world:
    name: "world"
    host: "127.0.0.1"
    port: 8083

actor:
  system: "overmind"
  host: "127.0.0.1"
  port: 9001

mongo:
  uri: "mongodb://127.0.0.1:27017"
  database: "overmind"

world:
  scene:
    width: 1000
    height: 1000
    cell_size: 100

log:
  level: "debug"
  encoding: "console"
