node:
  name: "world@127.0.0.1"
  cookie: "overmind_secret_cookie"
  listen_host: "127.0.0.1"
  listen_port: 15003
database:
  uri: "mongodb://127.0.0.1:27017"
  db_name: "overmind"
home_ring:
  version: 1
  nodes:
    - "home1@127.0.0.1"
  prev_nodes: []
