node:
  name: "world@127.0.0.1"
  cookie: "overmind_secret_cookie"
  listen_host: "127.0.0.1"
  listen_port: 15003
routes:
  - node_name: "gate@127.0.0.1"
    host: "127.0.0.1"
    port: 15001
  - node_name: "home1@127.0.0.1"
    host: "127.0.0.1"
    port: 15002
