// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/asynkron/protoactor-go/actor"
	"github.com/google/wire"
	"overmind/internal/gateway/net"
	"overmind/internal/kit/config"
)

// Injectors from wire.go:

// InitializeGateway 是 Wire 的注入入口
func InitializeGateway(cfg *config.Config) (*GatewayApp, error) {
	actorSystem := ProvideActorSystem()
	wsServer := ProvideWSServer(actorSystem, cfg)
	tcpServer := ProvideTCPServer(actorSystem, cfg)
	gatewayApp := NewGatewayApp(wsServer, tcpServer)
	return gatewayApp, nil
}

// wire.go:

// ProvideActorSystem 封装 NewActorSystem
func ProvideActorSystem() *actor.ActorSystem {
	return actor.NewActorSystem()
}

// ProvideWSServer 提供 WebSocket 服务
func ProvideWSServer(system *actor.ActorSystem, cfg *config.Config) *net.WSServer {
	return net.NewWSServer(fmt.Sprintf(":%d", cfg.Server.Port), system)
}

// ProvideTCPServer 提供 TCP 服务 (端口+1)
func ProvideTCPServer(system *actor.ActorSystem, cfg *config.Config) *net.TCPServer {

	return net.NewTCPServer(fmt.Sprintf(":%d", cfg.Server.Port+1), system)
}

// ProviderSet 定义 Gateway 的所有依赖
var ProviderSet = wire.NewSet(
	ProvideActorSystem,
	ProvideWSServer,
	ProvideTCPServer,
	NewGatewayApp,
)
