// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynkron/protoactor-go/actor"
	"github.com/google/wire"
	"overmind/internal/kit/config"
)

// Injectors from wire.go:

// InitializePortal 是 Wire 的注入入口
func InitializePortal(cfg *config.Config) (*PortalApp, error) {
	actorSystem := ProvideActorSystem()
	portalApp := NewPortalApp(actorSystem, cfg)
	return portalApp, nil
}

// wire.go:

// ProvideActorSystem 封装
func ProvideActorSystem() *actor.ActorSystem {
	return actor.NewActorSystem()
}

// ProviderSet 定义 Portal 的所有依赖
var ProviderSet = wire.NewSet(
	ProvideActorSystem,
	NewPortalApp,
)
